#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor2,          leftmotorsecond, tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor7,          rightmotorsecond, tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move(int Vl, int Vr, int Ti)
{
motor[motor1]=Vl;
motor[motor2]=Vl;
motor[motor6]=Vr;
motor[motor7]=Vr;
wait1Msec(Ti);


}
task main()
{
while (1)
{
	if (vexRT[BtnRUp]==1)//*!!движение вперед по нажатию правого верхнего бампера *!!//
	{
	move(50, 50, 2);

	}
	else
	{
		move(0, 0, 2);

	}


	if (vexRT[BtnLUp]==1)//*!!движение назад по нажатию левого верхнего бампера *!!//
	{
	move(-50, -50, 2);

	}
	else
	{
		move(0, 0, 2);

	}

	if (vexRT[BtnRDown]==1)//*!!разворот направо по нажатию правого нижнего бампера *!!//	
	{
	move(50, -50, 2);

	}
	else
	{
		move(0, 0, 2);

	}

	if (vexRT[BtnLDown]==1)//*!!разворот налево по нажатию левого нижнего бампера *!!//
	{
	move(-50, 50, 2);

	}
	else
	{
		move(0, 0, 2);

	}


}


}
